version: '3.7' # maybe

services:

  sample:
    container_name: ciuris.com
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - ${port}:${port} # from .env
    environment:
      - CHOKIDAR_USEPOLLING=true